INSERT INTO department (name)
VALUES  ('Human Resources'),
        ('Accounting'),
        ('Legal'),
        ('Tech Support'),
        ('Building Services');
        
INSERT INTO role (title, salary, department_id)
VALUES  ('Training and development', 60000, 1),
        ('Employee Relations', 65000, 1),
        ('Compensation and benefits', 70000, 1),
        ('Forensic accountant', 80000, 2),
        ('Tax advisor', 75000, 2),
        ('Payroll', 60000, 2),
        ('Partner', 120000, 3),
        ('Associate', 90000, 3),
        ('Secretarial', 50000, 3),
        ('Technical support specialist', 55000, 4),
        ('Technical support manager', 70000, 4),
        ('Maintenance', 45000, 5),
        ('Janitorial', 40000, 5);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ('Alice', 'Johnson', 1, NULL),
        ('Bob', 'Smith', 2, 1),
        ('Cathy', 'Lee', 3, 2),
        ('Daniel', 'Brown', 4, NULL),
        ('Ella', 'White', 5, 4),
        ('Frank', 'Clark', 6, 5),
        ('Grace', 'Wang', 7, NULL),
        ('Henry', 'Hall', 8, 7),
        ('Ivy', 'Turner', 9, 8),
        ('Jack', 'Walker', 10, NULL),
        ('Katherine', 'Young', 11, 10),
        ('Liam', 'Harris', 12, NULL),
        ('Mia', 'Lopez', 1, 2),
        ('Nathan', 'Allen', 2, 3),
        ('Olivia', 'King', 3, 1),
        ('Paul', 'Scott', 4, 8),
        ('Quinn', 'Adams', 5, 11),
        ('Riley', 'Baker', 6, 12),
        ('Sophie', 'Nelson', 7, 4),
        ('Thomas', 'Hill', 8, 7),
        ('Ursula', 'Carter', 9, 2),
        ('Victor', 'Morris', 10, 11),
        ('Wendy', 'Mitchell', 11, 9),
        ('Xander', 'Parker', 12, 6),
        ('Yvonne', 'Martin', 1, 8),
        ('Zachary', 'Rodriguez', 2, 5),
        ('Amy', 'Jackson', 3, 12),
        ('Brian', 'Gonzalez', 4, 9),
        ('Charlotte', 'Perez', 5, 10),
        ('David', 'Ramirez', 6, 1),
        ('Ella', 'Green', 7, 3),
        ('Frank', 'Bennett', 8, 4),
        ('Gina', 'Simmons', 9, 11),
        ('Henry', 'Cox', 10, 8),
        ('Irene', 'Perry', 11, 2),
        ('Jack', 'Cole', 12, 5);